### ISSUE TITLE
Styles tidy-up

### ISSUE THREAD

**Issue by codepotato** [Freegle/iznik-nuxt#2]
Are we okay to create a central stylesheet / sass file to run all the styles from, rather than inline to the vue-components?

**Comment by codepotato** [comment]
@edwh Am I okay to run through and centralise the styling of elements on this? You seem to have styles in a number of different places

**Comment by edwh** [comment]
I thought that the Vue "way" was to include most of the styles in the individual components to which they applied.

- So that you don't have to have two files open at once in your editor.
- So that you can use the "scoped" thing, which means you can make CSS changes in one component without fear of breaking other components.
- So that your style names are simple without having to put the component name in there to avoid clashes.
- Reduces load size a little.

I've checked and https://vuejs.org/v2/style-guide/#Component-style-scoping-essential kinda confirms that.

So I wouldn't be keen on moving all CSS out of components as a general rule.  Where CSS applies across multiple components then of course it makes sense to have it global, and there are some global CSS styles on style.css and user.less.  They are a bit of a mess and definitely need sorting out.
