### ISSUE TITLE
Suggestion: "similar terms" game only needs one button (also, might accept more than two items)

### ISSUE THREAD

**Issue by ConradHughes** [Freegle/iznik-nuxt#342]
The "similar terms" game currently has two buttons, "nothing similar" and "these are similar" (or something like that).  I have several times accidentally clicked "nothing similar" after I've selected two similar items, and the site has treated this as a fine thing to do.  It occurs to me that really you only need one button: with one or no terms selected it should say "nothing similar", while with two or more it should be "these are similar".

On a side note, it's currently not possible to identify three similar terms, even if there are three.  I guess given the request for "most similar", this is ok, but there have been occasions when I thought it appropriate to click three terms.

**Comment by edwh** [comment]
Thanks for the comments.  It's still a refreshing rarity when we get issues raised, so it's quite exciting :-).

Yes, you're right about the skip button.  Thanks, I'll fix that.

You will sometimes see more than two similar terms by chance, and I agree that sometimes you want to select them.  But it is pairs of terms that we're trying to identify in order to use that information to improve our searching.  

If you could select more than two, then I think we would dilute the quality of the information we get, because people may select things that are only vaguely similar because they think that the more they select, the more helpful it would be.
