### ISSUE TITLE
Make chats per-item, not per-member

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#384]
At the moment, chats are accessed (at least as far as the UI is concerned) on a per-member basis, i.e. there is one chat log for one member, no matter how many items you are discussing with them.

This has a few negative effects, in my opinion. For example, if you are discussing more than one item with a member at the same time, email notifications can get the wrong subject line, which can cause confusion and mistakes. Indeed, I'm not entirely sure how the system determines which subject line to use when you chat via the web UI.

So I propose that the Chats page shows a list of items being discussed, rather than a list of members. Two chats with the same member would display separately.

**Comment by edwh** [comment]
Quite a long time in the past we used to do this, and it generated a lot more confusion, e.g.
* people who didn't even realise they were talking to the same person in two different ways
* people putting messages relating to one item in the other chat, which meant the chats didn't make sense.

Like real conversations, people don't stay rigidly on topic.  For example:

- Hi, I'd like your sofa.
- Cool, would you like the cushions?
- Yes please, and I notice you have a rug, could I have that?
- Sure, when can you collect?
- Tomorrow for the cushions and the rug, if that's ok, but it'll be the weekend before I can organise a van for the sofa.  By the way, who do you fancy for the big match?
- ...later...do you have any more cushions, by any chance?

There isn't a way in which you can allocate these messages to a single item, because they can relate to one, multiple, or none of them.  It doesn't map neatly to the way people talk.

At the moment, the system picks the last reply in the chat to use for the subject line.  This isn't perfect, but having tried it both ways, this has fewer issues than the other ways.  

So we'll stick with this, I'm afraid.  But the My Posts page allows you to see a per-item view, where we can tie a chat to an item.
