### ISSUE TITLE
Zoomer doesn't show all of the image

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#398]
See this video:

https://user-images.githubusercontent.com/2512915/164104294-6113d825-1b3a-48de-9ac8-6021caa1be48.mp4

You may notice that I am not able to zoom into the bottom roughly one-third of the image.

**Comment by edwh** [comment]
Thanks.  I think it depends on where on the image you click.  You'd 
naturally tend to click on the area that you were interested in, though 
not always.

That may just be how the library we use works, but you could try raising 
an issue against https://github.com/samjonesigd/vue-image-zoomer.

------ Original Message ------
From: "John Veness" ***@***.***>
To: "Freegle/iznik-nuxt" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 19/04/2022 22:21:26
Subject: [Freegle/iznik-nuxt] Zoomer doesn't show all of the image 
(Issue #398)

**Comment by JohnVeness** [comment]
I've tried clicking in all sorts of places, with always the same effect. I've tested with several browsers.

I guess I could raise an issue there, but I suspect it will quickly get to the point where they ask how I'm using their code. As you're the direct "user" of their code, maybe you could raise an issue and answer any questions they bring up?

**Comment by edwh** [comment]
What's your viewport size?

https://whatismyviewport.com/

**Comment by JohnVeness** [comment]
Your viewport size is:
1419 × 796

DPR: 1.14

Screen Size: 1683 × 946

**Comment by edwh** [comment]
Thanks, I can reproduce this.  I think it's the least worst option, though.  

The popup is scaled so that it fits the screen without scrolling.  That has the consequence that you noticed.  

You can make zoom work to allow you to zoom at the edges, but only if you allow the image to overflow the screen and force a scroll.  The combination of scroll and zoom is pretty clunky, and that would make the experience worse more of the time - people would have to scroll fairly regularly on small screens.  

Wanting to be able to zoom at the edges of the image is less likely (though not impossible).

**Comment by JohnVeness** [comment]
On further testing, this seems to only be a problem when there is only one image in a post. When the carousel is in use, the zooming works fine.

**Comment by edwh** [comment]
That's interesting.  I've done a change to put a single image inside the carousel, which will be live after around 10:30 today.  Can you see if it helps?

**Comment by JohnVeness** [comment]
Yep, that seems to work fine now, thanks.

**Comment by edwh** [comment]
Great - thanks for helping improve this area.
